INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('1', 'Dog', 'Affenhuahua');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('2', 'Dog', 'Affenpinscher');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('3', 'Dog', 'Afghan Collie');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('4', 'Dog', 'Afghan Hound');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('5', 'Dog', 'Airedale Terrier');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('6', 'Dog', 'Airedoodle');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('7', 'Dog', 'Akbash');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('8', 'Dog', 'Akita');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('9', 'Dog', 'Akita Shepherd');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('10', 'Dog', 'Alapaha Blue Blood Bulldog');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('11', 'Dog', 'Alaskan Klee Kai');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('12', 'Dog', 'Alaskan Malamute');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('13', 'Dog', 'American Bandogge');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('14', 'Dog', 'American Bulldog');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('15', 'Dog', 'American Bully');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('16', 'Dog', 'American English Coonhound');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('17', 'Dog', 'American Eskimo Dog');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('18', 'Dog', 'American Foxhound');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('19', 'Dog', 'American Hairless Terrier');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('20', 'Dog', 'American Leopard Hound');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('21', 'Dog', 'American Mastiff');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('22', 'Dog', 'American Pit Bull Terrier');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('23', 'Dog', 'American Staffordshire Terrier');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('24', 'Dog', 'American Toy Terrier');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('25', 'Dog', 'American Water Spaniel');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('26', 'Dog', 'Anatolian Pyrenees');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('27', 'Dog', 'Anatolian Shepherd Dog');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('28', 'Dog', 'Appenzeller Sennenhund');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('29', 'Dog', 'Australian Cattle Dog');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('30', 'Dog', 'Australian Kelpie');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('31', 'Dog', 'Australian Retriever');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('32', 'Dog', 'Australian Shepherd');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('33', 'Dog', 'Australian Shepherd Husky');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('34', 'Dog', 'Australian Terrier');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('35', 'Dog', 'Australian Terrier Mix');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('36', 'Dog', 'Staffordshire Bull Terrier');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('37', 'Dog', 'Standard Schnauzer');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('38', 'Dog', 'Sussex Spaniel');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('39', 'Dog', 'Swedish Vallhund');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('40', 'Dog', 'Tibetan Mastiff');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('41', 'Dog', 'Tibetan Spaniel');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('42', 'Cat', 'Abyssinian');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('43', 'Cat', 'American Bobtail');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('44', 'Cat', 'American Bobtail Shorthair');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('45', 'Cat', 'American Curl');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('46', 'Cat', 'American Curl Longhair');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('47', 'Cat', 'American Shorthair');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('48', 'Cat', 'American Wirehair');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('49', 'Cat', 'Australian Mist');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('50', 'Cat', 'Balinese');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('51', 'Cat', 'Bengal');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('52', 'Cat', 'Bengal Longhair');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('53', 'Cat', 'Birman');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('54', 'Cat', 'Bombay');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('55', 'Cat', 'British Longhair');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('56', 'Cat', 'British Shorthair');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('57', 'Cat', 'Burmese');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('58', 'Cat', 'Burmilla');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('59', 'Cat', 'Burmilla Longhair');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('60', 'Cat', 'Chartreux');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('61', 'Cat', 'Chausie');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('62', 'Cat', 'Colorpoint Shorthair');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('63', 'Cat', 'Cornish Rex');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('64', 'Cat', 'Cymric');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('65', 'Cat', 'Devon Rex');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('66', 'Cat', 'Donskoy');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('67', 'Cat', 'LaPerm Shorthair');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('68', 'Cat', 'Lykoi');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('69', 'Cat', 'Manx');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('70', 'Cat', 'Maine Coon');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('71', 'Cat', 'Maine Coon Polydactyl');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('72', 'Cat', 'Minuet');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('73', 'Cat', 'Minuet Longhair');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('74', 'Cat', 'Munchkin');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('75', 'Cat', 'Munchkin Longhair');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('76', 'Cat', 'Nebelung');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('77', 'Cat', 'Norwegian Forest Cat');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('78', 'Cat', 'Ocicat');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('80', 'Cat', 'Oriental');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('82', 'Cat', 'Peterbald');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('83', 'Cat', 'Pixiebob');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('85', 'Cat', 'Pixiebob Longhair');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('86', 'Skinks', 'Garden Skink');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('87', 'Pet Bird', 'Canary');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('88', 'Pet Rabbit', 'Dwarf Hotot');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('89', 'Pet Hamster', 'Dwarf Hamster');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('90', 'Pet Rat', 'Cinnamon');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('91', 'Asian House Gecko', 'Asian House Gecko');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('92', 'Agamids', 'Bearded Dragon');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('93', 'Chameleons', 'Bitaeniatus Chameleon');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('94', 'Iguana', 'Blue Iguana');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('95', 'Anole', 'Bahaman Anole');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('96', 'Tegu', 'Argentine Red Tegu');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('97', 'Monitor', 'Ackie Monitor (Ridge-Tailed Monitor)');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('98', ' Guinea Pig', 'White Crested');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('99', 'Sugar Glider', 'Mosaic Sugar Glider');
INSERT INTO species_breed (species_breed_id, species, breed) VALUES ('100', 'Prairie Dog', 'Mexican Prairie Dog');