import { FlatList, View, StyleSheet } from 'react-native';
import Pet from '../components/schema/pet';

const styles = StyleSheet.create({
  separator: {
    height: 10,
  },
});

const pets = [

  {
    pet_id: 9,
    name: 'Arlo',
    photo: 'https://pamsdogtraining.com/wp-content/uploads/2022/07/long-haired-chihuahua-1024x683.jpg',
    pet_status: 'healthy',
    description: 'Playful and joyful',
    species_breed_id: 1,
    date_of_birth: '2022-12-12',
    gender: 'other',
    postal_code: 'V5N1L7',
    has_full_inmmune_shots: 0,
    is_pregnant: 0,
    avg_rating: 2.83,
    num_ratings: 23,
    looking_for: 'playdate',
    registered_time: '2024-05-25 19:28',
    is_neutered: 1
  },
  {
    pet_id: 7,
    name: 'Sherlock',
    photo: 'https://cdn.shopify.com/s/files/1/2668/1922/files/british-shorthair-1.jpg?v=1689089942',
    pet_status: 'healthy',
    description: 'Friendly with everyone',
    species_breed_id: 56,
    date_of_birth: '2021-03-09',
    gender: 'female',
    postal_code: 'V5M3T4',
    has_full_inmmune_shots: 0,
    is_pregnant: 0,
    avg_rating: 4.75,
    num_ratings: 3,
    looking_for: 'playdate',
    registered_time: '2024-01-23 08:47',
    is_neutered: 1
  },
  {
    pet_id: 17,
    name: 'Daisy',
    photo: 'https://www.dutch.com/cdn/shop/articles/shutterstock_1898629669.jpg?v=1697090094&width=1512',
    pet_status: 'healthy',
    description: 'Playful and curious',
    species_breed_id: NaN,
    date_of_birth: '54',
    gender: '2017-04-22',
    postal_code: 'other',
    has_full_inmmune_shots: NaN,
    is_pregnant: 1,
    avg_rating: 4,
    num_ratings: 22,
    looking_for: 'playdate',
    registered_time: '2024-02-06 21:00',
    is_neutered: 2024
  },
  {
      pet_id: 1,
      name: 'Mochi',
      photo: 'https://gundog-journal.com/siteimg/main/ugc-1/fullnews/news/155/182_original.jpg', // You can provide an actual image URL here
      date_of_birth: '2024-02-13',
      pet_status: 'healthy',
      description: 'Friendly and playful',
      species_breed_id: 1,
      gender: 'F',
      postal_code: 'V5L4S1',
      has_full_inmmune_shots: 1,
      is_pregnant: 0,
      avg_rating: 4.36,
      num_ratings: 10,
      looking_for: 'playdate',
      registered_time: '2024-04-02 19:13',
      is_neutered: 1,
    },
    {
      pet_id: 2,
      name: 'Noodle',
      photo: 'https://dogtime.com/wp-content/uploads/sites/12/2023/08/GettyImages-1435474615-1-e1691930474231.jpg?w=1024', // You can provide an actual image URL here
      date_of_birth: '2023-12-25',
      pet_status: 'healthy',
      description: 'Friendly and curious',
      species_breed_id: 2,
      gender: 'M',
      postal_code: 'V5M1Y4',
      has_full_inmmune_shots: 1,
      is_pregnant: 0,
      avg_rating: 4.42,
      num_ratings: 21,
      looking_for: 'playdate',
      registered_time: '2024-02-18 20:56',
      is_neutered: 1,
    },
    {
      pet_id: 3,
      name: 'Pepper',
      photo: 'https://cdn.shopify.com/s/files/1/0840/6049/files/0013_The_Australian_Shepherd.jpg?v=1676744966',
      pet_status: 'healthy',
      description: 'Enjoys playing fetch',
      species_breed_id: 33,
      date_of_birth: '2022-06-10',
      gender: 'female',
      postal_code: 'V5M1Z1',
      has_full_inmmune_shots: 1,
      is_pregnant: 0,
      avg_rating: 3.44,
      num_ratings: 32,
      looking_for: 'playdate',
      registered_time: '2024-03-13 13:23',
      is_neutered: 1
    },
    {
      pet_id: 4,
      name: 'Captain',
      photo: 'https://www.catster.com/wp-content/uploads/2023/11/ocicat-male-cat-on-light-beige-background_dien-Shutterstock.jpg.webp',
      pet_status: 'healthy',
      description: 'A loyal companion',
      species_breed_id: 78,
      date_of_birth: '2019-03-01',
      gender: 'male',
      postal_code: 'V5M1Z7',
      has_full_inmmune_shots: 1,
      is_pregnant: 0,
      avg_rating: 4.65,
      num_ratings: 14,
      looking_for: 'playdate',
      registered_time: '2024-05-18 21:12',
      is_neutered: 1
    },
    {
      pet_id: 5,
      name: 'Luna',
      photo: 'https://images.articlesfactory.com/750x0/8199f971-7c4a-40a4-820a-8914e89aafab.webp',
      pet_status: 'healthy',
      description: 'Curious and adventurous',
      species_breed_id: 5,
      date_of_birth: '2018-04-01',
      gender: 'female',
      postal_code: 'V5M2A1',
      has_full_inmmune_shots: 1,
      is_pregnant: 0,
      avg_rating: 2.1,
      num_ratings: 23,
      looking_for: 'playdate',
      registered_time: '2024-02-02 10:10',
      is_neutered: 1
    },
    {
      pet_id: 6,
      name: 'Kiwi',
      photo: 'https://dogtime.com/wp-content/uploads/sites/12/2011/01/GettyImages-1309830116-e1692992685110.jpg?w=1024',
      pet_status: 'healthy',
      description: 'Loves belly rubs',
      species_breed_id: 29,
      date_of_birth: '2022-05-05',
      gender: 'male',
      postal_code: 'V5M2B2',
      has_full_inmmune_shots: 0,
      is_pregnant: 0,
      avg_rating: 2.76,
      num_ratings: 6,
      looking_for: 'playdate',
      registered_time: '2024-04-25 12:51',
      is_neutered: 1
    },
    
    {
      pet_id: 8,
      name: 'Maple',
      photo: 'https://b3235999.smushcdn.com/3235999/wp-content/uploads/2023/11/dsc_9513-modifier-800x600.jpg?lossy=2&strip=1&webp=1',
      pet_status: 'healthy',
      description: 'Enjoys long walks',
      species_breed_id: 55,
      date_of_birth: '2024-01-01',
      gender: 'other',
      postal_code: 'V5N1C1',
      has_full_inmmune_shots: 0,
      is_pregnant: 0,
      avg_rating: 2.11,
      num_ratings: 5,
      looking_for: 'playdate',
      registered_time: '2024-04-22 05:39',
      is_neutered: 1
    },
  
    {
      pet_id: 10,
      name: 'Bumble',
      photo: 'https://www.thesprucepets.com/thmb/012WV_zdYYpMrw45dt4Ode6F5kY=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/GettyImages-1329847382-4448215c5efc4f9da320d2455c684d32.jpg',
      pet_status: 'healthy',
      description: 'Loves to be pampered',
      species_breed_id: 64,
      date_of_birth: '2022-11-09',
      gender: 'male',
      postal_code: 'V5N1W6',
      has_full_inmmune_shots: 0,
      is_pregnant: 0,
      avg_rating: 3.62,
      num_ratings: 16,
      looking_for: 'playdate',
      registered_time: '2024-02-03 22:58',
      is_neutered: 1
    },
    {
      pet_id: 11,
      name: 'Bella',
      photo: 'https://moderndogmagazine.com/wp-content/uploads/2016/02/20121216-_MG_4301.jpg',
      pet_status: 'bad mood',
      description: 'Loves attention and belly rubs',
      species_breed_id: 19,
      date_of_birth: '2019-05-15',
      gender: 'female',
      postal_code: 'V5N1Z9',
      has_full_inmmune_shots: 1,
      is_pregnant: 0,
      avg_rating: 4.23,
      num_ratings: 25,
      looking_for: 'playdate',
      registered_time: '2024-04-20 15:17',
      is_neutered: 1
    },
    {
      pet_id: 12,
      name: 'Max',
      photo: 'https://cdn.shopify.com/s/files/1/0326/4492/3436/files/standard-schnauzer_2_480x480.jpg?v=1619388251',
      pet_status: 'healthy',
      description: 'Energetic and loves running',
      species_breed_id: 37,
      date_of_birth: '2023-02-20',
      gender: 'male',
      postal_code: 'V5N2G2',
      has_full_inmmune_shots: 0,
      is_pregnant: 0,
      avg_rating: 4.58,
      num_ratings: 30,
      looking_for: 'playdate',
      registered_time: '2024-05-03 05:29',
      is_neutered: 1
    },
    {
      pet_id: 13,
      name: 'Luna',
      photo: 'https://www.thesprucepets.com/thmb/UPYN6rumtZv5mW4wLprNAs0lbbE=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/GettyImages-165827729-efc11c02690f457a81ef6ccbfa8eb34d.jpg',
      pet_status: 'healthy',
      description: 'Sweet and gentle',
      species_breed_id: NaN,
      date_of_birth: '42',
      gender: '2018-11-10',
      postal_code: 'female',
      has_full_inmmune_shots: NaN,
      is_pregnant: 1,
      avg_rating: 4.30,
      num_ratings: 4,
      looking_for: 'mate',
      registered_time: '2024-03-05 18:00',
      is_neutered: 1
    },
    {
      pet_id: 14,
      name: 'Charlie',
      photo: 'https://www.dogster.com/wp-content/uploads/2024/03/pitbull-wearing-red-collar_Mary-Swift_Shutterstock.jpg',
      pet_status: 'healthy',
      description: 'Loves playing fetch and going on hikes',
      species_breed_id: 22,
      date_of_birth: '2021-08-03',
      gender: 'other',
      postal_code: 'V5N2T7',
      has_full_inmmune_shots: 1,
      is_pregnant: 0,
      avg_rating: 4.72,
      num_ratings: 35,
      looking_for: 'playdate',
      registered_time: '2024-01-10 07:11',
      is_neutered: 1
    },
    {
      pet_id: 15,
      name: 'Lucy',
      photo: 'https://basepaws.com/_next/image?url=https%3A%2F%2Fimages.ctfassets.net%2F7hqiona4456t%2F6LG7MgWSZCGaV0WXeDg2SB%2F9817e8d9698d21d177aab92ed20ed6a6%2FLykoi_Cat.jpg&w=1080&q=75',
      pet_status: 'healthy',
      description: 'Affectionate and enjoys sunbathing',
      species_breed_id: 68,
      date_of_birth: '2019-12-28',
      gender: 'female',
      postal_code: 'V5N2Z9',
      has_full_inmmune_shots: 1,
      is_pregnant: 0,
      avg_rating: 4.35,
      num_ratings: 28,
      looking_for: 'playdate',
      registered_time: '2024-05-20 15:37',
      is_neutered: 1
    },
    {
      pet_id: 16,
      name: 'Cooper',
      photo: 'https://www.worldlifeexpectancy.com//images/a/d/d/b/akbash_dog/akbash_dog_1.webp',
      pet_status: 'healthy',
      description: 'Protective and loves car rides',
      species_breed_id: 7,
      date_of_birth: '2020-06-10',
      gender: 'male',
      postal_code: 'V5N3E8',
      has_full_inmmune_shots: 1,
      is_pregnant: 0,
      avg_rating: 4.61,
      num_ratings: 32,
      looking_for: 'playdate',
      registered_time: '2024-02-07 21:19',
      is_neutered: 1
    },
    {
      pet_id: 18,
      name: 'Duke',
      photo: 'https://images.ctfassets.net/440y9b545yd9/6YVNGk5u5Xgwzz02En0yrK/78d222f3633e7f0d7f82adb484bc8c59/Peterbald850.jpg',
      pet_status: 'bad mood',
      description: 'Active and enjoys long walks',
      species_breed_id: 82,
      date_of_birth: '2016-09-14',
      gender: 'male',
      postal_code: 'V5N5A5',
      has_full_inmmune_shots: 1,
      is_pregnant: 0,
      avg_rating: 4.43,
      num_ratings: 29,
      looking_for: 'playdate',
      registered_time: '2024-02-15 17:49',
      is_neutered: 1
    },
    {
      pet_id: 19,
      name: 'Zoe',
      photo: 'https://cdn.shortpixel.ai/spai/w_1240+q_lossy+ret_img+to_webp/betterpet.com/wp-content/uploads/2023/02/american-bully.jpeg',
      pet_status: 'healthy',
      description: 'Gentle and affectionate',
      species_breed_id: 15,
      date_of_birth: '15',
      gender: '2018-02-09',
      postal_code: 'female',
      has_full_inmmune_shots: 1,
      is_pregnant: 1,
      avg_rating: 3.32,
      num_ratings: 4,
      looking_for: 'mate',
      registered_time: '2024-02-15 17:49',
      is_neutered: 1
    },
    {
      pet_id: 20,
      name: 'Rocky',
      photo: 'https://www.thesprucepets.com/thmb/J74f38f-dbjPIBZe4z96Vx8QyuE=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/american-curl-full-profile-history-and-care-4705972-hero-2c9bdcfba3d84130b8eed233c46c19d3.jpg',
      pet_status: 'healthy',
      description: 'Playful and loves belly rubs',
      species_breed_id: 45,
      date_of_birth: '2015-11-30',
      gender: 'other',
      postal_code: 'V5P2V9',
      has_full_inmmune_shots: 1,
      is_pregnant: 0,
      avg_rating: 4.55,
      num_ratings: 31,
      looking_for: 'playdate',
      registered_time: '2024-04-11 21:56',
      is_neutered: 1
    }
    
  


];

const PetList = () => {
  
   return (
    pets.map((pet, index) => <Pet key={index} pet={pet} />)
    );
  
};

export default PetList;