import { FlatList, View, StyleSheet } from 'react-native';
import Pet from '../../pet';

const styles = StyleSheet.create({
  separator: {
    height: 10,
  },
});

const pets = [
  {
      pet_id: 1,
      name: 'Mochi',
      photo: 'https://d3ekkvinch1ig5.cloudfront.net/breed-thumb/1704024519.jpg.webp', // You can provide an actual image URL here
      date_of_birth: '2024-02-13',
      pet_status: 'healthy',
      description: 'Friendly and playful',
      species_breed_id: 1,
      gender: 'F',
      postal_code: 'V5L4S1',
      has_full_inmmune_shots: 1,
      is_pregnant: 0,
      avg_rating: 4.36,
      num_ratings: 10,
      looking_for: 'playdate',
      registered_time: '2024-04-02 19:13',
      is_neutered: 1,
    },
    {
      pet_id: 2,
      name: 'Noodle',
      photo: 'https://www.akc.org/wp-content/uploads/2017/11/Affenpinscher-illustration.jpg', // You can provide an actual image URL here
      date_of_birth: '2023-12-25',
      pet_status: 'healthy',
      description: 'Friendly and curious',
      species_breed_id: 2,
      gender: 'M',
      postal_code: 'V5M1Y4',
      has_full_inmmune_shots: 1,
      is_pregnant: 0,
      avg_rating: 4.42,
      num_ratings: 21,
      looking_for: 'playdate',
      registered_time: '2024-02-18 20:56',
      is_neutered: 1,
    },
    {
      pet_id: 3,
      name: 'Pepper',
      photo: null,
      pet_status: 'healthy',
      description: 'Enjoys playing fetch',
      species_breed_id: 33,
      date_of_birth: '2022-06-10',
      gender: 'female',
      postal_code: 'V5M1Z1',
      has_full_inmmune_shots: 1,
      is_pregnant: 0,
      avg_rating: 3.44,
      num_ratings: 32,
      looking_for: 'playdate',
      registered_time: '2024-03-13 13:23',
      is_neutered: 1
    },
    {
      pet_id: 4,
      name: 'Captain',
      photo: 'null',
      pet_status: 'healthy',
      description: 'A loyal companion',
      species_breed_id: 78,
      date_of_birth: '2019-03-01',
      gender: 'male',
      postal_code: 'V5M1Z7',
      has_full_inmmune_shots: 1,
      is_pregnant: 0,
      avg_rating: 4.65,
      num_ratings: 14,
      looking_for: 'playdate',
      registered_time: '2024-05-18 21:12',
      is_neutered: 1
    },
    {
      pet_id: 5,
      name: 'Luna',
      photo: 'null',
      pet_status: 'healthy',
      description: 'Curious and adventurous',
      species_breed_id: 5,
      date_of_birth: '2018-04-01',
      gender: 'female',
      postal_code: 'V5M2A1',
      has_full_inmmune_shots: 1,
      is_pregnant: 0,
      avg_rating: 2.1,
      num_ratings: 23,
      looking_for: 'playdate',
      registered_time: '2024-02-02 10:10',
      is_neutered: 1
    },
    {
      pet_id: 6,
      name: 'Kiwi',
      photo: 'null',
      pet_status: 'healthy',
      description: 'Loves belly rubs',
      species_breed_id: 29,
      date_of_birth: '2022-05-05',
      gender: 'male',
      postal_code: 'V5M2B2',
      has_full_inmmune_shots: 0,
      is_pregnant: 0,
      avg_rating: 2.76,
      num_ratings: 6,
      looking_for: 'playdate',
      registered_time: '2024-04-25 12:51',
      is_neutered: 1
    },
    {
      pet_id: 7,
      name: 'Sherlock',
      photo: 'null',
      pet_status: 'healthy',
      description: 'Friendly with everyone',
      species_breed_id: 56,
      date_of_birth: '2021-03-09',
      gender: 'female',
      postal_code: 'V5M3T4',
      has_full_inmmune_shots: 0,
      is_pregnant: 0,
      avg_rating: 4.75,
      num_ratings: 3,
      looking_for: 'playdate',
      registered_time: '2024-01-23 08:47',
      is_neutered: 1
    },
    {
      pet_id: 8,
      name: 'Maple',
      photo: 'null',
      pet_status: 'healthy',
      description: 'Enjoys long walks',
      species_breed_id: 55,
      date_of_birth: '2024-01-01',
      gender: 'other',
      postal_code: 'V5N1C1',
      has_full_inmmune_shots: 0,
      is_pregnant: 0,
      avg_rating: 2.11,
      num_ratings: 5,
      looking_for: 'playdate',
      registered_time: '2024-04-22 05:39',
      is_neutered: 1
    },
    {
      pet_id: 9,
      name: 'Arlo',
      photo: 'null',
      pet_status: 'healthy',
      description: 'Playful and joyful',
      species_breed_id: 1,
      date_of_birth: '2022-12-12',
      gender: 'other',
      postal_code: 'V5N1L7',
      has_full_inmmune_shots: 0,
      is_pregnant: 0,
      avg_rating: 2.83,
      num_ratings: 23,
      looking_for: 'playdate',
      registered_time: '2024-05-25 19:28',
      is_neutered: 1
    },
    {
      pet_id: 10,
      name: 'Bumble',
      photo: 'null',
      pet_status: 'healthy',
      description: 'Loves to be pampered',
      species_breed_id: 64,
      date_of_birth: '2022-11-09',
      gender: 'male',
      postal_code: 'V5N1W6',
      has_full_inmmune_shots: 0,
      is_pregnant: 0,
      avg_rating: 3.62,
      num_ratings: 16,
      looking_for: 'playdate',
      registered_time: '2024-02-03 22:58',
      is_neutered: 1
    },
    {
      pet_id: 11,
      name: 'Bella',
      photo: 'null',
      pet_status: 'bad mood',
      description: 'Loves attention and belly rubs',
      species_breed_id: 19,
      date_of_birth: '2019-05-15',
      gender: 'female',
      postal_code: 'V5N1Z9',
      has_full_inmmune_shots: 1,
      is_pregnant: 0,
      avg_rating: 4.23,
      num_ratings: 25,
      looking_for: 'playdate',
      registered_time: '2024-04-20 15:17',
      is_neutered: 1
    },
    {
      pet_id: 12,
      name: 'Max',
      photo: 'null',
      pet_status: 'healthy',
      description: 'Energetic and loves running',
      species_breed_id: 37,
      date_of_birth: '2023-02-20',
      gender: 'male',
      postal_code: 'V5N2G2',
      has_full_inmmune_shots: 0,
      is_pregnant: 0,
      avg_rating: 4.58,
      num_ratings: 30,
      looking_for: 'playdate',
      registered_time: '2024-05-03 05:29',
      is_neutered: 1
    },
    {
      pet_id: 13,
      name: 'Luna',
      photo: 'null',
      pet_status: 'healthy',
      description: '"Sweet and gentle',
      species_breed_id: NaN,
      date_of_birth: '42',
      gender: '2018-11-10',
      postal_code: 'female',
      has_full_inmmune_shots: NaN,
      is_pregnant: 1,
      avg_rating: 0,
      num_ratings: 4,
      looking_for: '20',
      registered_time: 'mate',
      is_neutered: 2024
    },
    {
      pet_id: 14,
      name: 'Charlie',
      photo: 'null',
      pet_status: 'healthy',
      description: 'Loves playing fetch and going on hikes',
      species_breed_id: 22,
      date_of_birth: '2021-08-03',
      gender: 'other',
      postal_code: 'V5N2T7',
      has_full_inmmune_shots: 1,
      is_pregnant: 0,
      avg_rating: 4.72,
      num_ratings: 35,
      looking_for: 'playdate',
      registered_time: '2024-01-10 07:11',
      is_neutered: 1
    },
    {
      pet_id: 15,
      name: 'Lucy',
      photo: 'null',
      pet_status: 'healthy',
      description: 'Affectionate and enjoys sunbathing',
      species_breed_id: 68,
      date_of_birth: '2019-12-28',
      gender: 'female',
      postal_code: 'V5N2Z9',
      has_full_inmmune_shots: 1,
      is_pregnant: 0,
      avg_rating: 4.35,
      num_ratings: 28,
      looking_for: 'playdate',
      registered_time: '2024-05-20 15:37',
      is_neutered: 1
    },
    {
      pet_id: 16,
      name: 'Cooper',
      photo: 'null',
      pet_status: 'healthy',
      description: 'Protective and loves car rides',
      species_breed_id: 7,
      date_of_birth: '2020-06-10',
      gender: 'male',
      postal_code: 'V5N3E8',
      has_full_inmmune_shots: 1,
      is_pregnant: 0,
      avg_rating: 4.61,
      num_ratings: 32,
      looking_for: 'playdate',
      registered_time: '2024-02-07 21:19',
      is_neutered: 1
    },
    {
      pet_id: 17,
      name: 'Daisy',
      photo: 'null',
      pet_status: 'healthy',
      description: '"Playful and curious',
      species_breed_id: NaN,
      date_of_birth: '54',
      gender: '2017-04-22',
      postal_code: 'other',
      has_full_inmmune_shots: NaN,
      is_pregnant: 1,
      avg_rating: 0,
      num_ratings: 4,
      looking_for: '22',
      registered_time: 'playdate',
      is_neutered: 2024
    },
    {
      pet_id: 18,
      name: 'Duke',
      photo: 'null',
      pet_status: 'bad mood',
      description: 'Active and enjoys long walks',
      species_breed_id: 82,
      date_of_birth: '2016-09-14',
      gender: 'male',
      postal_code: 'V5N5A5',
      has_full_inmmune_shots: 1,
      is_pregnant: 0,
      avg_rating: 4.43,
      num_ratings: 29,
      looking_for: 'playdate',
      registered_time: '2024-02-15 17:49',
      is_neutered: 1
    },
    {
      pet_id: 19,
      name: 'Zoe',
      photo: 'null',
      pet_status: 'healthy',
      description: '"Gentle and affectionate',
      species_breed_id: NaN,
      date_of_birth: '15',
      gender: '2018-02-09',
      postal_code: 'female',
      has_full_inmmune_shots: NaN,
      is_pregnant: 1,
      avg_rating: 0,
      num_ratings: 4,
      looking_for: '24',
      registered_time: 'mate',
      is_neutered: 2024
    },
    {
      pet_id: 20,
      name: 'Rocky',
      photo: 'null',
      pet_status: 'healthy',
      description: 'Playful and loves belly rubs',
      species_breed_id: 45,
      date_of_birth: '2015-11-30',
      gender: 'other',
      postal_code: 'V5P2V9',
      has_full_inmmune_shots: 1,
      is_pregnant: 0,
      avg_rating: 4.55,
      num_ratings: 31,
      looking_for: 'playdate',
      registered_time: '2024-04-11 21:56',
      is_neutered: 1
    },
    {
      pet_id: 21,
      name: 'Sadie',
      photo: 'null',
      pet_status: 'healthy',
      description: 'Energetic and enjoys playing fetch',
      species_breed_id: 6,
      date_of_birth: '2017-07-18',
      gender: 'other',
      postal_code: 'V5R2A5',
      has_full_inmmune_shots: 1,
      is_pregnant: 0,
      avg_rating: 4.36,
      num_ratings: 27,
      looking_for: 'playdate',
      registered_time: '2024-03-08 21:44',
      is_neutered: 1
    },
    {
      pet_id: 22,
      name: 'Oscar',
      photo: 'null',
      pet_status: 'healthy',
      description: 'Sweet and loves meeting new friends',
      species_breed_id: 31,
      date_of_birth: '2019-03-05',
      gender: 'male',
      postal_code: 'V5R2J2',
      has_full_inmmune_shots: 1,
      is_pregnant: 0,
      avg_rating: 4.62,
      num_ratings: 33,
      looking_for: 'playdate',
      registered_time: '2024-04-30 02:07',
      is_neutered: 1
    },
    {
      pet_id: 23,
      name: 'Ruby',
      photo: 'null',
      pet_status: 'healthy',
      description: 'Calm and enjoys relaxing in the sun',
      species_breed_id: 71,
      date_of_birth: '2016-01-17',
      gender: 'female',
      postal_code: 'V5R2J8',
      has_full_inmmune_shots: 1,
      is_pregnant: 0,
      avg_rating: 4.15,
      num_ratings: 23,
      looking_for: 'playdate',
      registered_time: '2024-04-09 23:51',
      is_neutered: 1
    },
    {
      pet_id: 24,
      name: 'Teddy',
      photo: 'null',
      pet_status: 'healthy',
      description: 'Playful and loves attention',
      species_breed_id: 11,
      date_of_birth: '2022-11-29',
      gender: 'male',
      postal_code: 'V5R2K4',
      has_full_inmmune_shots: 0,
      is_pregnant: 0,
      avg_rating: 4.43,
      num_ratings: 28,
      looking_for: 'playdate',
      registered_time: '2024-03-09 14:38',
      is_neutered: 1
    },
    {
      pet_id: 25,
      name: 'Lily',
      photo: 'null',
      pet_status: 'healthy',
      description: 'Affectionate and enjoys walks',
      species_breed_id: 16,
      date_of_birth: '2018-06-03',
      gender: 'female',
      postal_code: 'V5R2S3',
      has_full_inmmune_shots: 1,
      is_pregnant: 0,
      avg_rating: 4.25,
      num_ratings: 25,
      looking_for: 'playdate',
      registered_time: '2024-01-19 19:52',
      is_neutered: 1
    },
    {
      pet_id: 26,
      name: 'Winston',
      photo: 'null',
      pet_status: 'healthy',
      description: 'Energetic and loves playing outside',
      species_breed_id: 76,
      date_of_birth: '2019-09-20',
      gender: 'male',
      postal_code: 'V5R2S6',
      has_full_inmmune_shots: 1,
      is_pregnant: 0,
      avg_rating: 4.53,
      num_ratings: 30,
      looking_for: 'playdate',
      registered_time: '2024-04-16 04:57',
      is_neutered: 1
    },
    {
      pet_id: 27,
      name: 'Coco',
      photo: 'null',
      pet_status: 'bad mood',
      description: 'Playful and loves belly rubs',
      species_breed_id: 18,
      date_of_birth: '2023-12-12',
      gender: 'other',
      postal_code: 'V5R3N8',
      has_full_inmmune_shots: 0,
      is_pregnant: 0,
      avg_rating: 4.15,
      num_ratings: 21,
      looking_for: 'mate',
      registered_time: '2024-04-16 04:53',
      is_neutered: 1
    },
    {
      pet_id: 28,
      name: 'Murphy',
      photo: 'null',
      pet_status: 'healthy',
      description: 'Loves going on hikes and swimming',
      species_breed_id: 41,
      date_of_birth: '2016-04-05',
      gender: 'male',
      postal_code: 'V5R3W4',
      has_full_inmmune_shots: 1,
      is_pregnant: 0,
      avg_rating: 4.72,
      num_ratings: 36,
      looking_for: 'playdate',
      registered_time: '2024-03-19 03:13',
      is_neutered: 1
    },
    {
      pet_id: 29,
      name: 'Mia',
      photo: 'null',
      pet_status: 'healthy',
      description: 'Friendly and loves meeting new people',
      species_breed_id: 4,
      date_of_birth: '2015-02-18',
      gender: 'other',
      postal_code: 'V5R4J5',
      has_full_inmmune_shots: 1,
      is_pregnant: 0,
      avg_rating: 4.33,
      num_ratings: 29,
      looking_for: 'playdate',
      registered_time: '2024-04-06 10:55',
      is_neutered: 1
    },
    {
      pet_id: 30,
      name: 'Bailey',
      photo: 'null',
      pet_status: 'sick',
      description: 'Loves playing with toys',
      species_breed_id: 2,
      date_of_birth: '2016-07-08',
      gender: 'male',
      postal_code: 'V5R4J6',
      has_full_inmmune_shots: 1,
      is_pregnant: 0,
      avg_rating: 4.64,
      num_ratings: 32,
      looking_for: 'playdate',
      registered_time: '2024-05-01 19:40',
      is_neutered: 1
    },
    {
      pet_id: 31,
      name: 'Rosie',
      photo: 'null',
      pet_status: 'healthy',
      description: 'Sweet and loves cuddling',
      species_breed_id: 34,
      date_of_birth: '2018-03-25',
      gender: 'female',
      postal_code: 'V5R4J8',
      has_full_inmmune_shots: 1,
      is_pregnant: 0,
      avg_rating: 4.18,
      num_ratings: 22,
      looking_for: 'playdate',
      registered_time: '2024-02-04 06:25',
      is_neutered: 1
    },
    {
      pet_id: 32,
      name: 'Milo',
      photo: 'null',
      pet_status: 'healthy',
      description: 'Energetic and enjoys outdoor walks',
      species_breed_id: 58,
      date_of_birth: '2021-02-08',
      gender: 'male',
      postal_code: 'V5R4S8',
      has_full_inmmune_shots: 1,
      is_pregnant: 0,
      avg_rating: 3.98,
      num_ratings: 29,
      looking_for: 'playdate',
      registered_time: '2024-01-24 00:54',
      is_neutered: 1
    },
    {
      pet_id: 33,
      name: 'Chloe',
      photo: 'null',
      pet_status: 'healthy',
      description: 'Loves to run and play fetch',
      species_breed_id: 74,
      date_of_birth: '2019-10-20',
      gender: 'female',
      postal_code: 'V5R5G8',
      has_full_inmmune_shots: 1,
      is_pregnant: 0,
      avg_rating: 4.22,
      num_ratings: 24,
      looking_for: 'playdate',
      registered_time: '2024-05-11 01:54',
      is_neutered: 1
    },
    {
      pet_id: 34,
      name: 'Tucker',
      photo: 'null',
      pet_status: 'healthy',
      description: 'Friendly and playful',
      species_breed_id: 21,
      date_of_birth: '2020-07-15',
      gender: 'male',
      postal_code: 'V5R6H8',
      has_full_inmmune_shots: 1,
      is_pregnant: 0,
      avg_rating: 3.88,
      num_ratings: 31,
      looking_for: 'playdate',
      registered_time: '2024-02-27 21:25',
      is_neutered: 1
    },
    {
      pet_id: 35,
      name: 'Bailey',
      photo: 'null',
      pet_status: 'healthy',
      description: 'Loves to climb and explore',
      species_breed_id: 65,
      date_of_birth: '2018-05-03',
      gender: 'female',
      postal_code: 'V5S0H2',
      has_full_inmmune_shots: 1,
      is_pregnant: 0,
      avg_rating: 4.12,
      num_ratings: 28,
      looking_for: 'playdate',
      registered_time: '2024-01-15 15:11',
      is_neutered: 1
    },
    {
      pet_id: 36,
      name: 'Charlie',
      photo: 'null',
      pet_status: 'healthy',
      description: 'Sings beautifully in the morning',
      species_breed_id: 4,
      date_of_birth: '2021-03-31',
      gender: 'male',
      postal_code: 'V5R3W4',
      has_full_inmmune_shots: 1,
      is_pregnant: 0,
      avg_rating: 4.36,
      num_ratings: 11,
      looking_for: 'playdate',
      registered_time: '2024-04-15 15:50',
      is_neutered: 1
    },
    {
      pet_id: 37,
      name: 'Whisker',
      photo: 'null',
      pet_status: 'sick',
      description: 'Fierce but loving',
      species_breed_id: 49,
      date_of_birth: '2022-09-20',
      gender: 'female',
      postal_code: 'V6A0E3',
      has_full_inmmune_shots: 0,
      is_pregnant: 0,
      avg_rating: 4.03,
      num_ratings: 19,
      looking_for: 'playdate',
      registered_time: '2024-05-07 00:51',
      is_neutered: 1
    },
    {
      pet_id: 38,
      name: 'Chirpy',
      photo: 'null',
      pet_status: 'healthy',
      description: 'Soft and cuddly',
      species_breed_id: 80,
      date_of_birth: '2019-06-10',
      gender: 'female',
      postal_code: 'V5V4P4',
      has_full_inmmune_shots: 1,
      is_pregnant: 0,
      avg_rating: 4.67,
      num_ratings: 30,
      looking_for: 'mate',
      registered_time: '2024-04-04 14:35',
      is_neutered: 1
    },
    {
      pet_id: 39,
      name: 'Lumos',
      photo: 'null',
      pet_status: 'bad mood',
      description: 'Quiet and mysterious',
      species_breed_id: 27,
      date_of_birth: '2020-06-25',
      gender: 'male',
      postal_code: 'V5X2T9',
      has_full_inmmune_shots: 1,
      is_pregnant: 0,
      avg_rating: 3.75,
      num_ratings: 14,
      looking_for: 'mate',
      registered_time: '2024-02-13 05:00',
      is_neutered: 1
    },
    {
      pet_id: 40,
      name: 'Fluffy',
      photo: 'null',
      pet_status: 'healthy',
      description: 'Small but energetic',
      species_breed_id: 38,
      date_of_birth: '2022-11-02',
      gender: 'female',
      postal_code: 'V5R4J5',
      has_full_inmmune_shots: 1,
      is_pregnant: 0,
      avg_rating: 4.68,
      num_ratings: 26,
      looking_for: 'playdate',
      registered_time: '2024-05-24 02:16',
      is_neutered: 1
    },
    {
      pet_id: 41,
      name: 'Slither',
      photo: 'null',
      pet_status: 'healthy',
      description: 'Colorful and cheerful',
      species_breed_id: 17,
      date_of_birth: '2020-02-14',
      gender: 'female',
      postal_code: 'V5R4J6',
      has_full_inmmune_shots: 1,
      is_pregnant: 0,
      avg_rating: 4.21,
      num_ratings: 10,
      looking_for: 'playdate',
      registered_time: '2024-01-15 22:36',
      is_neutered: 1
    },
    {
      pet_id: 42,
      name: 'Nibbles',
      photo: 'null',
      pet_status: 'healthy',
      description: 'Protective and brave',
      species_breed_id: 9,
      date_of_birth: '2023-01-01',
      gender: 'male',
      postal_code: 'V5R4J8',
      has_full_inmmune_shots: 1,
      is_pregnant: 0,
      avg_rating: 4.58,
      num_ratings: 38,
      looking_for: 'playdate',
      registered_time: '2024-04-06 22:40',
      is_neutered: 1
    },
    {
      pet_id: 43,
      name: 'Tweety',
      photo: 'null',
      pet_status: 'healthy',
      description: 'Curious and playful',
      species_breed_id: 32,
      date_of_birth: '2019-07-21',
      gender: 'female',
      postal_code: 'V5X0J5',
      has_full_inmmune_shots: 1,
      is_pregnant: 0,
      avg_rating: 4.72,
      num_ratings: 27,
      looking_for: 'playdate',
      registered_time: '2024-03-26 03:34',
      is_neutered: 1
    },
    {
      pet_id: 44,
      name: 'Spike',
      photo: 'null',
      pet_status: 'healthy',
      description: 'Energetic and loyal',
      species_breed_id: 17,
      date_of_birth: '2018-10-30',
      gender: 'male',
      postal_code: 'V5Y0B7',
      has_full_inmmune_shots: 1,
      is_pregnant: 0,
      avg_rating: 4.85,
      num_ratings: 39,
      looking_for: 'playdate',
      registered_time: '2024-05-13 12:54',
      is_neutered: 1
    },
    {
      pet_id: 45,
      name: 'Bubbles',
      photo: 'null',
      pet_status: 'healthy',
      description: 'Loves to explore new places',
      species_breed_id: 14,
      date_of_birth: '2021-03-15',
      gender: 'female',
      postal_code: 'V5X2J4',
      has_full_inmmune_shots: 1,
      is_pregnant: 0,
      avg_rating: 4.73,
      num_ratings: 32,
      looking_for: 'playdate',
      registered_time: '2024-02-17 06:15',
      is_neutered: 1
    },
    {
      pet_id: 46,
      name: 'Nyx',
      photo: 'null',
      pet_status: 'healthy',
      description: 'Loves to dig and play',
      species_breed_id: 66,
      date_of_birth: '2020-01-10',
      gender: 'male',
      postal_code: 'V5Y0B7',
      has_full_inmmune_shots: 1,
      is_pregnant: 0,
      avg_rating: 4.35,
      num_ratings: 24,
      looking_for: 'mate',
      registered_time: '2024-02-10 13:38',
      is_neutered: 1
    },
    {
      pet_id: 47,
      name: 'Daisy',
      photo: 'null',
      pet_status: 'bad mood',
      description: 'Brave and protective with a big heart',
      species_breed_id: 3,
      date_of_birth: '2019-09-30',
      gender: 'female',
      postal_code: 'V5Z2C3',
      has_full_inmmune_shots: 1,
      is_pregnant: 0,
      avg_rating: 4.32,
      num_ratings: 18,
      looking_for: 'mate',
      registered_time: '2024-04-22 10:44',
      is_neutered: 1
    },
    {
      pet_id: 48,
      name: 'Tiny',
      photo: 'null',
      pet_status: 'healthy',
      description: 'Friendly and playful',
      species_breed_id: 46,
      date_of_birth: '2022-05-08',
      gender: 'male',
      postal_code: 'V6A4E1',
      has_full_inmmune_shots: 1,
      is_pregnant: 0,
      avg_rating: 4.1,
      num_ratings: 13,
      looking_for: 'playdate',
      registered_time: '2024-02-10 18:41',
      is_neutered: 1
    },
    {
      pet_id: 49,
      name: 'Saffron',
      photo: 'null',
      pet_status: 'sick',
      description: 'Loves to cuddle',
      species_breed_id: 41,
      date_of_birth: '2018-06-11',
      gender: 'male',
      postal_code: 'V6B0P4',
      has_full_inmmune_shots: 1,
      is_pregnant: 0,
      avg_rating: 4.82,
      num_ratings: 38,
      looking_for: 'playdate',
      registered_time: '2024-03-16 12:47',
      is_neutered: 1
    },
    {
      pet_id: 50,
      name: 'Bella',
      photo: 'null',
      pet_status: 'healthy',
      description: 'Energetic and curious',
      species_breed_id: 24,
      date_of_birth: '2020-05-20',
      gender: 'female',
      postal_code: 'V5N1Z9',
      has_full_inmmune_shots: 1,
      is_pregnant: 0,
      avg_rating: 4.5,
      num_ratings: 45,
      looking_for: 'playdate',
      registered_time: '2024-02-03 17:06',
      is_neutered: 1
    },
    {
      pet_id: 51,
      name: 'Charlie',
      photo: 'null',
      pet_status: 'bad mood',
      description: 'Loves outdoor activities',
      species_breed_id: 40,
      date_of_birth: '2019-08-12',
      gender: 'male',
      postal_code: 'V5S2G2',
      has_full_inmmune_shots: 0,
      is_pregnant: 0,
      avg_rating: 4.7,
      num_ratings: 42,
      looking_for: 'playdate',
      registered_time: '2024-03-29 11:56',
      is_neutered: 1
    },
    {
      pet_id: 52,
      name: 'Max',
      photo: 'null',
      pet_status: 'sick',
      description: 'Affectionate and gentle',
      species_breed_id: 82,
      date_of_birth: '2021-02-25',
      gender: 'male',
      postal_code: 'V5T2R8',
      has_full_inmmune_shots: 1,
      is_pregnant: 0,
      avg_rating: 4.6,
      num_ratings: 37,
      looking_for: 'playdate',
      registered_time: '2024-02-12 12:00',
      is_neutered: 1
    },
    {
      pet_id: 53,
      name: 'Luna',
      photo: 'null',
      pet_status: 'healthy',
      description: 'Loyal and protective',
      species_breed_id: 16,
      date_of_birth: '2018-11-30',
      gender: 'female',
      postal_code: 'V5N2T7',
      has_full_inmmune_shots: 0,
      is_pregnant: 0,
      avg_rating: 4.8,
      num_ratings: 28,
      looking_for: 'playdate',
      registered_time: '2024-04-23 18:03',
      is_neutered: 1
    },
    {
      pet_id: 54,
      name: 'Lucy',
      photo: 'null',
      pet_status: 'bad mood',
      description: 'Playful and intelligent',
      species_breed_id: 40,
      date_of_birth: '2020-07-14',
      gender: 'female',
      postal_code: 'V5N2Z9',
      has_full_inmmune_shots: 1,
      is_pregnant: 0,
      avg_rating: 4.9,
      num_ratings: 34,
      looking_for: 'playdate',
      registered_time: '2024-03-07 14:35',
      is_neutered: 1
    },
    {
      pet_id: 55,
      name: 'Cooper',
      photo: 'null',
      pet_status: 'sick',
      description: 'Gentle and sweet',
      species_breed_id: 67,
      date_of_birth: '2019-09-21',
      gender: 'male',
      postal_code: 'V5S3E8',
      has_full_inmmune_shots: 0,
      is_pregnant: 0,
      avg_rating: 4.4,
      num_ratings: 30,
      looking_for: 'playdate',
      registered_time: '2024-02-11 18:31',
      is_neutered: 1
    },
    {
      pet_id: 56,
      name: 'Milo',
      photo: 'null',
      pet_status: 'healthy',
      description: 'Energetic and playful',
      species_breed_id: 8,
      date_of_birth: '2020-01-10',
      gender: 'male',
      postal_code: 'V5T1Z9',
      has_full_inmmune_shots: 1,
      is_pregnant: 0,
      avg_rating: 4.7,
      num_ratings: 39,
      looking_for: 'playdate',
      registered_time: '2024-05-22 01:15',
      is_neutered: 1
    },
    {
      pet_id: 57,
      name: 'Daisy',
      photo: 'null',
      pet_status: 'bad mood',
      description: 'Protective and loyal',
      species_breed_id: 36,
      date_of_birth: '2019-04-05',
      gender: 'female',
      postal_code: 'V5N2G2',
      has_full_inmmune_shots: 1,
      is_pregnant: 0,
      avg_rating: 4.5,
      num_ratings: 41,
      looking_for: 'playdate',
      registered_time: '2024-02-17 17:05',
      is_neutered: 1
    },
    {
      pet_id: 58,
      name: 'Bailey',
      photo: 'null',
      pet_status: 'sick',
      description: 'Friendly and active',
      species_breed_id: 70,
      date_of_birth: '2018-03-22',
      gender: 'female',
      postal_code: 'V5S2R8',
      has_full_inmmune_shots: 0,
      is_pregnant: 0,
      avg_rating: 4.6,
      num_ratings: 36,
      looking_for: 'mate',
      registered_time: '2024-03-21 06:20',
      is_neutered: 1
    },
    {
      pet_id: 59,
      name: 'Rocky',
      photo: 'null',
      pet_status: 'healthy',
      description: 'Curious and playful',
      species_breed_id: 23,
      date_of_birth: '2020-08-16',
      gender: 'male',
      postal_code: 'V5T2T7',
      has_full_inmmune_shots: 1,
      is_pregnant: 0,
      avg_rating: 4.8,
      num_ratings: 48,
      looking_for: 'playdate',
      registered_time: '2024-02-01 00:13',
      is_neutered: 1
    },
    {
      pet_id: 60,
      name: 'Zoe',
      photo: 'null',
      pet_status: 'bad mood',
      description: 'Loves to explore',
      species_breed_id: 52,
      date_of_birth: '2019-06-14',
      gender: 'female',
      postal_code: 'V5N2Z9',
      has_full_inmmune_shots: 1,
      is_pregnant: 0,
      avg_rating: 4.7,
      num_ratings: 30,
      looking_for: 'playdate',
      registered_time: '2024-05-16 00:54',
      is_neutered: 1
    },
    {
      pet_id: 61,
      name: 'Oscar',
      photo: 'null',
      pet_status: 'sick',
      description: 'Playful and energetic',
      species_breed_id: 79,
      date_of_birth: '2018-12-01',
      gender: 'male',
      postal_code: 'V5S3E8',
      has_full_inmmune_shots: 0,
      is_pregnant: 0,
      avg_rating: 4.5,
      num_ratings: 29,
      looking_for: 'playdate',
      registered_time: '2024-01-18 00:31',
      is_neutered: 1
    },
    {
      pet_id: 62,
      name: 'Sadie',
      photo: 'null',
      pet_status: 'healthy',
      description: 'Affectionate and friendly',
      species_breed_id: 13,
      date_of_birth: '2021-04-20',
      gender: 'female',
      postal_code: 'V5T1Z9',
      has_full_inmmune_shots: 1,
      is_pregnant: 0,
      avg_rating: 4.9,
      num_ratings: 34,
      looking_for: 'playdate',
      registered_time: '2024-01-28 22:00',
      is_neutered: 1
    },
    {
      pet_id: 63,
      name: 'Buddy',
      photo: 'null',
      pet_status: 'bad mood',
      description: 'Loves to run and play',
      species_breed_id: 55,
      date_of_birth: '2018-05-10',
      gender: 'male',
      postal_code: 'V5N2G2',
      has_full_inmmune_shots: 1,
      is_pregnant: 0,
      avg_rating: 4.6,
      num_ratings: 35,
      looking_for: 'playdate',
      registered_time: '2024-02-19 22:23',
      is_neutered: 1
    },
    {
      pet_id: 64,
      name: 'Lola',
      photo: 'null',
      pet_status: 'sick',
      description: 'Gentle and loving',
      species_breed_id: 75,
      date_of_birth: '2020-09-12',
      gender: 'female',
      postal_code: 'V5S2R8',
      has_full_inmmune_shots: 0,
      is_pregnant: 0,
      avg_rating: 4.7,
      num_ratings: 39,
      looking_for: 'playdate',
      registered_time: '2024-03-25 21:19',
      is_neutered: 1
    },
    {
      pet_id: 65,
      name: 'Jack',
      photo: 'null',
      pet_status: 'healthy',
      description: 'Playful and energetic',
      species_breed_id: 17,
      date_of_birth: '2019-11-22',
      gender: 'male',
      postal_code: 'V5T2T7',
      has_full_inmmune_shots: 1,
      is_pregnant: 0,
      avg_rating: 4.5,
      num_ratings: 42,
      looking_for: 'playdate',
      registered_time: '2024-04-22 06:50',
      is_neutered: 1
    },
    {
      pet_id: 66,
      name: 'Chloe',
      photo: 'null',
      pet_status: 'bad mood',
      description: 'Loyal and protective',
      species_breed_id: 43,
      date_of_birth: '2021-01-07',
      gender: 'female',
      postal_code: 'V5N2Z9',
      has_full_inmmune_shots: 1,
      is_pregnant: 0,
      avg_rating: 4.9,
      num_ratings: 48,
      looking_for: 'playdate',
      registered_time: '2024-04-13 05:51',
      is_neutered: 1
    },
    {
      pet_id: 67,
      name: 'Toby',
      photo: 'null',
      pet_status: 'sick',
      description: 'Curious and playful',
      species_breed_id: 63,
      date_of_birth: '2020-02-14',
      gender: 'male',
      postal_code: 'V5S3E8',
      has_full_inmmune_shots: 0,
      is_pregnant: 0,
      avg_rating: 4.6,
      num_ratings: 44,
      looking_for: 'playdate',
      registered_time: '2024-03-22 01:56',
      is_neutered: 1
    },
    {
      pet_id: 68,
      name: 'Riley',
      photo: 'null',
      pet_status: 'healthy',
      description: 'Loves to explore',
      species_breed_id: 10,
      date_of_birth: '2018-07-19',
      gender: 'female',
      postal_code: 'V5T1Z9',
      has_full_inmmune_shots: 1,
      is_pregnant: 0,
      avg_rating: 4.8,
      num_ratings: 32,
      looking_for: 'playdate',
      registered_time: '2024-04-19 12:45',
      is_neutered: 1
    },
    {
      pet_id: 69,
      name: 'Buster',
      photo: 'null',
      pet_status: 'bad mood',
      description: 'Playful and energetic',
      species_breed_id: 48,
      date_of_birth: '2019-03-25',
      gender: 'male',
      postal_code: 'V5N2G2',
      has_full_inmmune_shots: 1,
      is_pregnant: 0,
      avg_rating: 4.7,
      num_ratings: 30,
      looking_for: 'playdate',
      registered_time: '2024-03-22 01:40',
      is_neutered: 1
    },
    {
      pet_id: 70,
      name: 'Lily',
      photo: 'null',
      pet_status: 'sick',
      description: 'Affectionate and gentle',
      species_breed_id: 28,
      date_of_birth: '2020-06-01',
      gender: 'female',
      postal_code: 'V5S2R8',
      has_full_inmmune_shots: 0,
      is_pregnant: 0,
      avg_rating: 4.9,
      num_ratings: 34,
      looking_for: 'playdate',
      registered_time: '2024-01-03 21:43',
      is_neutered: 1
    },
    {
      pet_id: 71,
      name: 'Duke',
      photo: 'null',
      pet_status: 'healthy',
      description: 'Loyal and protective',
      species_breed_id: 18,
      date_of_birth: '2019-12-30',
      gender: 'male',
      postal_code: 'V5T2T7',
      has_full_inmmune_shots: 1,
      is_pregnant: 0,
      avg_rating: 4.6,
      num_ratings: 39,
      looking_for: 'playdate',
      registered_time: '2024-03-22 05:36',
      is_neutered: 1
    },
    {
      pet_id: 72,
      name: 'Zoey',
      photo: 'null',
      pet_status: 'bad mood',
      description: 'Friendly and playful',
      species_breed_id: 20,
      date_of_birth: '2018-08-16',
      gender: 'female',
      postal_code: 'V5N2Z9',
      has_full_inmmune_shots: 1,
      is_pregnant: 0,
      avg_rating: 4.7,
      num_ratings: 33,
      looking_for: 'playdate',
      registered_time: '2024-02-18 04:56',
      is_neutered: 1
    },
    {
      pet_id: 73,
      name: 'Bentley',
      photo: 'null',
      pet_status: 'sick',
      description: 'Loves to cuddle',
      species_breed_id: 59,
      date_of_birth: '2021-09-12',
      gender: 'male',
      postal_code: 'V5S3E8',
      has_full_inmmune_shots: 0,
      is_pregnant: 0,
      avg_rating: 4.5,
      num_ratings: 45,
      looking_for: 'playdate',
      registered_time: '2024-02-28 00:30',
      is_neutered: 1
    },
    {
      pet_id: 74,
      name: 'Daisy',
      photo: 'null',
      pet_status: 'healthy',
      description: 'Energetic and curious',
      species_breed_id: 35,
      date_of_birth: '2019-05-20',
      gender: 'female',
      postal_code: 'V5T1Z9',
      has_full_inmmune_shots: 1,
      is_pregnant: 0,
      avg_rating: 4.7,
      num_ratings: 31,
      looking_for: 'playdate',
      registered_time: '2024-03-18 06:48',
      is_neutered: 1
    },
    {
      pet_id: 75,
      name: 'Murphy',
      photo: 'null',
      pet_status: 'bad mood',
      description: 'Loves outdoor activities',
      species_breed_id: 60,
      date_of_birth: '2020-08-12',
      gender: 'female',
      postal_code: 'V5N2G2',
      has_full_inmmune_shots: 1,
      is_pregnant: 0,
      avg_rating: 4.9,
      num_ratings: 46,
      looking_for: 'playdate',
      registered_time: '2024-04-13 20:40',
      is_neutered: 1
    },
    {
      pet_id: 76,
      name: 'Coco',
      photo: 'null',
      pet_status: 'sick',
      description: 'Affectionate and gentle',
      species_breed_id: 25,
      date_of_birth: '2021-02-25',
      gender: 'male',
      postal_code: 'V5S2R8',
      has_full_inmmune_shots: 0,
      is_pregnant: 0,
      avg_rating: 4.6,
      num_ratings: 40,
      looking_for: 'playdate',
      registered_time: '2024-01-10 02:57',
      is_neutered: 1
    },
    {
      pet_id: 77,
      name: 'Molly',
      photo: 'null',
      pet_status: 'healthy',
      description: 'Loyal and protective',
      species_breed_id: 77,
      date_of_birth: '2018-11-30',
      gender: 'female',
      postal_code: 'V5T2T7',
      has_full_inmmune_shots: 1,
      is_pregnant: 0,
      avg_rating: 4.8,
      num_ratings: 35,
      looking_for: 'playdate',
      registered_time: '2024-03-12 03:00',
      is_neutered: 1
    },
    {
      pet_id: 78,
      name: 'Teddy',
      photo: 'null',
      pet_status: 'bad mood',
      description: 'Playful and intelligent',
      species_breed_id: 44,
      date_of_birth: '2020-07-14',
      gender: 'male',
      postal_code: 'V5N2Z9',
      has_full_inmmune_shots: 1,
      is_pregnant: 0,
      avg_rating: 4.9,
      num_ratings: 47,
      looking_for: 'playdate',
      registered_time: '2024-01-25 12:49',
      is_neutered: 1
    },
    {
      pet_id: 79,
      name: 'Lola',
      photo: 'null',
      pet_status: 'sick',
      description: 'Gentle and sweet',
      species_breed_id: 30,
      date_of_birth: '2019-09-21',
      gender: 'male',
      postal_code: 'V5S3E8',
      has_full_inmmune_shots: 0,
      is_pregnant: 0,
      avg_rating: 4.4,
      num_ratings: 29,
      looking_for: 'playdate',
      registered_time: '2024-05-09 19:19',
      is_neutered: 1
    },
    {
      pet_id: 80,
      name: 'Oliver',
      photo: 'null',
      pet_status: 'healthy',
      description: 'Energetic and playful',
      species_breed_id: 69,
      date_of_birth: '2020-01-10',
      gender: 'male',
      postal_code: 'V5T1Z9',
      has_full_inmmune_shots: 1,
      is_pregnant: 0,
      avg_rating: 4.7,
      num_ratings: 36,
      looking_for: 'playdate',
      registered_time: '2024-04-21 14:01',
      is_neutered: 1
    },
    {
      pet_id: 81,
      name: 'Harley',
      photo: 'null',
      pet_status: 'bad mood',
      description: 'Protective and loyal',
      species_breed_id: 26,
      date_of_birth: '2019-04-05',
      gender: 'female',
      postal_code: 'V5N2G2',
      has_full_inmmune_shots: 1,
      is_pregnant: 0,
      avg_rating: 4.5,
      num_ratings: 37,
      looking_for: 'playdate',
      registered_time: '2024-01-29 07:00',
      is_neutered: 1
    },
    {
      pet_id: 82,
      name: 'Zeus',
      photo: 'null',
      pet_status: 'sick',
      description: '"Quick and agile',
      species_breed_id: NaN,
      date_of_birth: '51',
      gender: '2018-03-22',
      postal_code: 'female',
      has_full_inmmune_shots: NaN,
      is_pregnant: 0,
      avg_rating: 0,
      num_ratings: 4,
      looking_for: '35',
      registered_time: 'playdate',
      is_neutered: 2024
    },
    {
      pet_id: 83,
      name: 'Maggie',
      photo: 'null',
      pet_status: 'healthy',
      description: '"Sings beautifully',
      species_breed_id: NaN,
      date_of_birth: '39',
      gender: '2020-08-16',
      postal_code: 'male',
      has_full_inmmune_shots: NaN,
      is_pregnant: 1,
      avg_rating: 0,
      num_ratings: 4,
      looking_for: '48',
      registered_time: 'playdate',
      is_neutered: 2024
    },
    {
      pet_id: 84,
      name: 'Nala',
      photo: 'null',
      pet_status: 'bad mood',
      description: '"Small and gentle',
      species_breed_id: NaN,
      date_of_birth: '57',
      gender: '2019-06-14',
      postal_code: 'female',
      has_full_inmmune_shots: NaN,
      is_pregnant: 1,
      avg_rating: 0,
      num_ratings: 4,
      looking_for: '39',
      registered_time: 'playdate',
      is_neutered: 2024
    },
    {
      pet_id: 85,
      name: 'Winston',
      photo: 'null',
      pet_status: 'sick',
      description: '"Tiny and curious',
      species_breed_id: NaN,
      date_of_birth: '42',
      gender: '2018-12-01',
      postal_code: 'male',
      has_full_inmmune_shots: NaN,
      is_pregnant: 0,
      avg_rating: 0,
      num_ratings: 4,
      looking_for: '28',
      registered_time: 'playdate',
      is_neutered: 2024
    },
    {
      pet_id: 86,
      name: 'Sophie',
      photo: 'null',
      pet_status: 'healthy',
      description: '"Intelligent and playful',
      species_breed_id: NaN,
      date_of_birth: '91',
      gender: '2021-04-20',
      postal_code: 'female',
      has_full_inmmune_shots: NaN,
      is_pregnant: 1,
      avg_rating: 0,
      num_ratings: 4,
      looking_for: '34',
      registered_time: 'playdate',
      is_neutered: 2024
    },
    {
      pet_id: 87,
      name: 'Rusty',
      photo: 'null',
      pet_status: 'bad mood',
      description: '"Agile climber',
      species_breed_id: NaN,
      date_of_birth: '87',
      gender: '2018-05-10',
      postal_code: 'male',
      has_full_inmmune_shots: NaN,
      is_pregnant: 1,
      avg_rating: 0,
      num_ratings: 4,
      looking_for: '38',
      registered_time: 'playdate',
      is_neutered: 2024
    },
    {
      pet_id: 88,
      name: 'Ellie',
      photo: 'null',
      pet_status: 'sick',
      description: '"Calm and gentle',
      species_breed_id: NaN,
      date_of_birth: '84',
      gender: '2020-09-12',
      postal_code: 'female',
      has_full_inmmune_shots: NaN,
      is_pregnant: 0,
      avg_rating: 0,
      num_ratings: 4,
      looking_for: '41',
      registered_time: 'playdate',
      is_neutered: 2024
    },
    {
      pet_id: 89,
      name: 'Sam',
      photo: 'null',
      pet_status: 'healthy',
      description: '"Active and colorful',
      species_breed_id: NaN,
      date_of_birth: '93',
      gender: '2019-11-22',
      postal_code: 'male',
      has_full_inmmune_shots: NaN,
      is_pregnant: 1,
      avg_rating: 0,
      num_ratings: 4,
      looking_for: '42',
      registered_time: 'playdate',
      is_neutered: 2024
    },
    {
      pet_id: 90,
      name: 'Penny',
      photo: 'null',
      pet_status: 'bad mood',
      description: '"Large and powerful',
      species_breed_id: NaN,
      date_of_birth: '88',
      gender: '2021-01-07',
      postal_code: 'male',
      has_full_inmmune_shots: NaN,
      is_pregnant: 1,
      avg_rating: 0,
      num_ratings: 4,
      looking_for: '45',
      registered_time: 'playdate',
      is_neutered: 2024
    },
    {
      pet_id: 91,
      name: 'Henry',
      photo: 'null',
      pet_status: 'sick',
      description: '"Fast and alert',
      species_breed_id: NaN,
      date_of_birth: '96',
      gender: '2020-02-14',
      postal_code: 'female',
      has_full_inmmune_shots: NaN,
      is_pregnant: 0,
      avg_rating: 0,
      num_ratings: 4,
      looking_for: '36',
      registered_time: 'playdate',
      is_neutered: 2024
    },
    {
      pet_id: 92,
      name: 'Duke',
      photo: 'null',
      pet_status: 'healthy',
      description: '"Friendly and docile',
      species_breed_id: NaN,
      date_of_birth: '89',
      gender: '2018-07-19',
      postal_code: 'male',
      has_full_inmmune_shots: NaN,
      is_pregnant: 1,
      avg_rating: 0,
      num_ratings: 4,
      looking_for: '32',
      registered_time: 'playdate',
      is_neutered: 2024
    },
    {
      pet_id: 93,
      name: 'Lola',
      photo: 'null',
      pet_status: 'bad mood',
      description: '"Energetic and playful',
      species_breed_id: NaN,
      date_of_birth: '100',
      gender: '2019-03-25',
      postal_code: 'female',
      has_full_inmmune_shots: NaN,
      is_pregnant: 1,
      avg_rating: 0,
      num_ratings: 4,
      looking_for: '29',
      registered_time: 'playdate',
      is_neutered: 2024
    },
    {
      pet_id: 94,
      name: 'Oscar',
      photo: 'null',
      pet_status: 'sick',
      description: '"Affectionate and social',
      species_breed_id: NaN,
      date_of_birth: '92',
      gender: '2020-06-01',
      postal_code: 'female',
      has_full_inmmune_shots: NaN,
      is_pregnant: 0,
      avg_rating: 0,
      num_ratings: 4,
      looking_for: '34',
      registered_time: 'playdate',
      is_neutered: 2024
    },
    {
      pet_id: 95,
      name: 'Molly',
      photo: 'null',
      pet_status: 'healthy',
      description: '"Active and playful',
      species_breed_id: NaN,
      date_of_birth: '86',
      gender: '2019-12-30',
      postal_code: 'male',
      has_full_inmmune_shots: NaN,
      is_pregnant: 1,
      avg_rating: 0,
      num_ratings: 4,
      looking_for: '39',
      registered_time: 'playdate',
      is_neutered: 2024
    },
    {
      pet_id: 96,
      name: 'Bailey',
      photo: 'null',
      pet_status: 'bad mood',
      description: '"Social and intelligent',
      species_breed_id: NaN,
      date_of_birth: '98',
      gender: '2018-08-16',
      postal_code: 'female',
      has_full_inmmune_shots: NaN,
      is_pregnant: 1,
      avg_rating: 0,
      num_ratings: 4,
      looking_for: '33',
      registered_time: 'playdate',
      is_neutered: 2024
    },
    {
      pet_id: 97,
      name: 'Teddy',
      photo: 'null',
      pet_status: 'sick',
      description: '"Active and intelligent',
      species_breed_id: NaN,
      date_of_birth: '90',
      gender: '2021-09-12',
      postal_code: 'male',
      has_full_inmmune_shots: NaN,
      is_pregnant: 0,
      avg_rating: 0,
      num_ratings: 4,
      looking_for: '40',
      registered_time: 'playdate',
      is_neutered: 2024
    },
    {
      pet_id: 98,
      name: 'Luna',
      photo: 'null',
      pet_status: 'healthy',
      description: '"Calm and friendly',
      species_breed_id: NaN,
      date_of_birth: '95',
      gender: '2019-05-20',
      postal_code: 'female',
      has_full_inmmune_shots: NaN,
      is_pregnant: 1,
      avg_rating: 0,
      num_ratings: 4,
      looking_for: '37',
      registered_time: 'playdate',
      is_neutered: 2024
    },
    {
      pet_id: 99,
      name: 'Jack',
      photo: 'null',
      pet_status: 'bad mood',
      description: '"Playful and intelligent',
      species_breed_id: NaN,
      date_of_birth: '97',
      gender: '2020-08-12',
      postal_code: 'male',
      has_full_inmmune_shots: NaN,
      is_pregnant: 1,
      avg_rating: 0,
      num_ratings: 4,
      looking_for: '46',
      registered_time: 'playdate',
      is_neutered: 2024
    },
    {
      pet_id: 100,
      name: 'Lucy',
      photo: 'null',
      pet_status: 'sick',
      description: '"Calm and gentle',
      species_breed_id: NaN,
      date_of_birth: '94',
      gender: '2021-02-25',
      postal_code: 'female',
      has_full_inmmune_shots: NaN,
      is_pregnant: 0,
      avg_rating: 0,
      num_ratings: 4,
      looking_for: '40',
      registered_time: 'playdate',
      is_neutered: 2024
    },
    {
      pet_id: 101,
      name: 'Shadow',
      photo: 'null',
      pet_status: 'healthy',
      description: 'Playful and loves to chase toys.',
      species_breed_id: 44,
      date_of_birth: '2021-07-25',
      gender: 'Female',
      postal_code: 'V5L4S1',
      has_full_inmmune_shots: 0,
      is_pregnant: 0,
      avg_rating: 4.02,
      num_ratings: 12,
      looking_for: 'date',
      registered_time: '2024-03-25 10:05',
      is_neutered: 1
    },
    {
      pet_id: 102,
      name: 'Sunny',
      photo: 'null',
      pet_status: 'healthy',
      description: 'Enjoys lounging in sunny spots.',
      species_breed_id: 76,
      date_of_birth: '2020-03-21',
      gender: 'Male',
      postal_code: 'V5M1Y4',
      has_full_inmmune_shots: 1,
      is_pregnant: 0,
      avg_rating: 4.53,
      num_ratings: 16,
      looking_for: 'playdate',
      registered_time: '2024-04-15 14:30',
      is_neutered: 1
    },
    {
      pet_id: 103,
      name: 'Simba',
      photo: 'null',
      pet_status: 'healthy',
      description: 'Curious and loves to explore.',
      species_breed_id: 32,
      date_of_birth: '2019-12-15',
      gender: 'Male',
      postal_code: 'V5M1Z1',
      has_full_inmmune_shots: 1,
      is_pregnant: 0,
      avg_rating: 4.68,
      num_ratings: 25,
      looking_for: 'playdate',
      registered_time: '2024-03-28 10:37',
      is_neutered: 1
    },
    {
      pet_id: 104,
      name: 'Milo',
      photo: 'null',
      pet_status: 'healthy',
      description: 'Loves a good scratch behind the ears.',
      species_breed_id: 41,
      date_of_birth: '2021-04-08',
      gender: 'Male',
      postal_code: 'V5M1Z7',
      has_full_inmmune_shots: 1,
      is_pregnant: 0,
      avg_rating: 4.67,
      num_ratings: 21,
      looking_for: 'playdate',
      registered_time: '2024-03-12 12:40',
      is_neutered: 1
    },
    {
      pet_id: 105,
      name: 'Lola',
      photo: 'null',
      pet_status: 'healthy',
      description: 'Energetic and loves to run around.',
      species_breed_id: 56,
      date_of_birth: '2022-10-22',
      gender: 'Female',
      postal_code: 'V5M2A1',
      has_full_inmmune_shots: 1,
      is_pregnant: 0,
      avg_rating: 4.31,
      num_ratings: 26,
      looking_for: 'date',
      registered_time: '2024-04-17 13:45',
      is_neutered: 1
    },
    {
      pet_id: 106,
      name: 'Ziggy',
      photo: 'null',
      pet_status: 'bad mood',
      description: 'Gentle and enjoys being brushed.',
      species_breed_id: 24,
      date_of_birth: '2020-08-30',
      gender: 'Female',
      postal_code: 'V5M2B2',
      has_full_inmmune_shots: 1,
      is_pregnant: 0,
      avg_rating: 4.62,
      num_ratings: 31,
      looking_for: 'playdate',
      registered_time: '2024-03-02 14:40',
      is_neutered: 1
    },
    {
      pet_id: 107,
      name: 'Peanut',
      photo: 'null',
      pet_status: 'healthy',
      description: 'Loves to cuddle and nap.',
      species_breed_id: 28,
      date_of_birth: '2023-05-05',
      gender: 'Male',
      postal_code: 'V5M3T4',
      has_full_inmmune_shots: 1,
      is_pregnant: 0,
      avg_rating: 4.38,
      num_ratings: 10,
      looking_for: 'playdate',
      registered_time: '2024-04-04 14:50',
      is_neutered: 1
    },
    {
      pet_id: 108,
      name: 'Gizmo',
      photo: 'null',
      pet_status: 'healthy',
      description: 'Adventurous and loves to climb.',
      species_breed_id: 21,
      date_of_birth: '2022-06-06',
      gender: 'Female',
      postal_code: 'V5N1C1',
      has_full_inmmune_shots: 1,
      is_pregnant: 0,
      avg_rating: 4.46,
      num_ratings: 21,
      looking_for: 'playdate',
      registered_time: '2024-04-28 15:20',
      is_neutered: 1
    },
    {
      pet_id: 109,
      name: 'Finn',
      photo: 'null',
      pet_status: 'healthy',
      description: 'Always ready for a treat.',
      species_breed_id: 17,
      date_of_birth: '2021-03-03',
      gender: 'Male',
      postal_code: 'V5N1L7',
      has_full_inmmune_shots: 1,
      is_pregnant: 0,
      avg_rating: 4.59,
      num_ratings: 15,
      looking_for: 'playdate',
      registered_time: '2024-04-21 16:00',
      is_neutered: 1
    },
    {
      pet_id: 110,
      name: 'Athena',
      photo: 'null',
      pet_status: 'healthy',
      description: 'Enjoys quiet time and relaxation.',
      species_breed_id: 4,
      date_of_birth: '2018-10-08',
      gender: 'Female',
      postal_code: 'V5N1W6',
      has_full_inmmune_shots: 0,
      is_pregnant: 0,
      avg_rating: 4.41,
      num_ratings: 9,
      looking_for: 'date',
      registered_time: '2024-05-11 13:21',
      is_neutered: 1
    },
    {
      pet_id: 111,
      name: 'Zephyr',
      photo: 'null',
      pet_status: 'healthy',
      description: 'Loves to play hide and seek.',
      species_breed_id: 8,
      date_of_birth: '2023-12-23',
      gender: 'Male',
      postal_code: 'V5N1Z9',
      has_full_inmmune_shots: 1,
      is_pregnant: 0,
      avg_rating: 4.52,
      num_ratings: 26,
      looking_for: 'playdate',
      registered_time: '2024-02-26 15:15',
      is_neutered: 1
    },
    {
      pet_id: 112,
      name: 'Shadow',
      photo: 'null',
      pet_status: 'healthy',
      description: 'Friendly and loves meeting new friends.',
      species_breed_id: 10,
      date_of_birth: '2021-07-25',
      gender: 'Female',
      postal_code: 'V5N2G2',
      has_full_inmmune_shots: 0,
      is_pregnant: 0,
      avg_rating: 4.02,
      num_ratings: 12,
      looking_for: 'date',
      registered_time: '2024-03-25 10:05',
      is_neutered: 1
    },
    {
      pet_id: 113,
      name: 'Sunny',
      photo: 'null',
      pet_status: 'healthy',
      description: 'Protective and always alert.',
      species_breed_id: 8,
      date_of_birth: '2020-03-21',
      gender: 'Male',
      postal_code: 'V5N2R8',
      has_full_inmmune_shots: 1,
      is_pregnant: 0,
      avg_rating: 4.53,
      num_ratings: 16,
      looking_for: 'playdate',
      registered_time: '2024-04-15 14:30',
      is_neutered: 1
    },
    {
      pet_id: 114,
      name: 'Simba',
      photo: 'null',
      pet_status: 'healthy',
      description: 'Loves to snuggle under blankets.',
      species_breed_id: 38,
      date_of_birth: '2019-12-15',
      gender: 'Male',
      postal_code: 'V5N2T7',
      has_full_inmmune_shots: 1,
      is_pregnant: 0,
      avg_rating: 4.68,
      num_ratings: 25,
      looking_for: 'playdate',
      registered_time: '2024-03-28 10:37',
      is_neutered: 1
    },
    {
      pet_id: 115,
      name: 'Milo',
      photo: 'null',
      pet_status: 'healthy',
      description: 'Energetic and loves to play fetch.',
      species_breed_id: 55,
      date_of_birth: '2021-04-08',
      gender: 'Male',
      postal_code: 'V5N2Z9',
      has_full_inmmune_shots: 1,
      is_pregnant: 0,
      avg_rating: 4.67,
      num_ratings: 21,
      looking_for: 'playdate',
      registered_time: '2024-03-12 12:40',
      is_neutered: 1
    },
    {
      pet_id: 116,
      name: 'Lola',
      photo: 'null',
      pet_status: 'healthy',
      description: 'Playful and loves to chase toys.',
      species_breed_id: 38,
      date_of_birth: '2022-10-22',
      gender: 'Female',
      postal_code: 'V5N3E8',
      has_full_inmmune_shots: 1,
      is_pregnant: 0,
      avg_rating: 4.31,
      num_ratings: 26,
      looking_for: 'date',
      registered_time: '2024-04-17 13:45',
      is_neutered: 1
    }
    
,

  


];

const PetList = () => {
  
   return (
    pets.map((pet, index) => <Pet key={index} pet={pet} />)
    );
  
};

export default PetList;